= Core

== Comments

[source,javascript]
----
/*
   comment
*/
----

[source,javascript]
----
// comment
----

== Variables

=== `var` vs `let`

https://stackoverflow.com/questions/762011/what-is-the-difference-between-let-and-var[What is the difference between "let" and "var"?]

===  `typeof` Operator

== Data Types

https://masteringjs.io/tutorials/fundamentals/primitives

Javascript has seven primitive data types:

* `string`
* `number`
* `bigint`
* `boolean`
* `undefined`
* `symbol`
* `null`

In JavaScript, a primitive is any value that isn't an object.

The `typeof` operator tells you what type a primitive value is.


[,https://www.geeksforgeeks.org/javascript-data-types/]
____
In JavaScript, each value has a data type, defining its nature (e.g., Number, String, Boolean) and operations. 
Data types are categorized into Primitive (e.g., String, Number) and Non-Primitive (e.g., Objects, Arrays).
____

[,https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Data_structures]
____
All primitive types, except `null` and `undefined`, have their corresponding object wrapper types, which provide useful methods for working with the primitive values. 
For example, the `Number` object provides methods like `toExponential()`. 
When a property is accessed on a primitive value, JavaScript automatically wraps the value into the corresponding wrapper object and accesses the property on the object instead. 
However, accessing a property on `null` or `undefined` throws a `TypeError` exception, which necessitates the introduction of the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining[optional chaining] operator.
____

|===
| Type | `typeof` return value | Object wrapper

| Null
| `"object"`
| N/A

| Undefined
| `"undefined"`
| N/A

| Boolean
| `"boolean"`
| `Boolean`

| Number
| `"number"`
| `Number`

| BigInt
| `"bigint"`
| `BigInt`

| String
| `"string"`
| `String`

| Symbol
| `"symbol"`
| `Symbol`
|===

[comment]
--
JavaScript has 8 data types:

=== String

=== Number

=== Bigint

=== Boolean

=== Undefined

=== Null

=== Symbol

=== Object 
--