= ECMAScript

https://en.wikipedia.org/wiki/ECMAScript[[wiki\]]

https://24ways.org/2014/javascript-modules-the-es6-way/

[cols=2*<]
|===
|4th Edition
|abandoned

|5th Edition
|ECMAScript 2009

|6th Edition
|ECMAScript 2015

|7th Edition
|ECMAScript 2016

|8th Edition
|ECMAScript 2017

|9th Edition
|ECMAScript 2018

|10th Edition
|ECMAScript 2019

|11th Edition
|ECMAScript 2020

|12th Edition
|ECMAScript 2021

|13th Edition
|ECMAScript 2022
|===

[,Gemini]
____
ECMAScript 2015, more commonly known as ES6, was indeed a monumental release for JavaScript for several key reasons. 
It wasn't just an incremental update; 
it introduced a vast array of new features and paradigms that fundamentally changed how JavaScript code is written, organized, and understood.
____

== node

....
SyntaxError: Cannot use import statement outside a module
....

https://stackoverflow.com/questions/62488898/node-js-syntaxerror-cannot-use-import-statement-outside-a-module

[source,bash]
----
pnpm init
----

[source,javascript,title="package.json"]
----
{
  // ...
  "type": "module",
  // ...
}
----

== Syntax

> "when I discuss a module, all I really mean is a JavaScript file."
-- https://24ways.org/2014/javascript-modules-the-es6-way/

> "Modules can export multiple objects, which can be either plain old variables or JavaScript functions."
-- https://24ways.org/2014/javascript-modules-the-es6-way/

=== Named Export

==== Example 1

[source,javascript,title="MyModule.js"]
----
let double = function(x) {
  return x + x;
}

let square = function(x) {
  return x * x;
}

export { double, square }
----

[source,javascript,title="Main.js"]
----
import { double, square } from 'MyModule.js';

double(2);
square(3);
----

==== Example 2

[source,javascript,title="MyModule.js"]
----
export function double(x) {
    return x + x;
};

export function square(x) {
    return x * x;
}
----

[source,javascript,title="Main.js"]
----
import { double, square } from 'MyModule.js';

double(2);
square(3);
----

=== Default Export

> "A module can define its default export (it can only ever have one default export)"
-- https://24ways.org/2014/javascript-modules-the-es6-way/

[source,javascript,title="MyModule.js"]
----
export default function(x) {
    return x + x;
}

export function square(x) {
    return x * x;
}
----

[source,javascript,title="Main.js"]
----
import double, { square } from 'MyModule.js';

console.log(double(2));
console.log(square(3));
----

[IMPORTANT]
====
[,Gemini]
____

[,javascript]
----
export default const subtract
----

is not allowed in JavaScript. 
You can't use `export default` with a `const`, `let`, or `var` declaration in a single statement. 
This is because `export default` is a statement that provides a single, main export for a module, while `const` (and other variable declarations) also defines a named identifier.

To achieve the desired behavior, you must separate the declaration from the export statement.

The Correct Ways: 

Define the variable first, then export it as the default:

[source,javascript,title="Main.js"]
----
const subtract = (a, b) => a - b;

export default subtract;
----

Use an arrow function without a variable name directly in the default export:

[source,javascript,title="Main.js"]
----
export default (a, b) => a - b;
----

This is a common and concise way to export a function anonymously as the default export.

Use a named function declaration:

[source,javascript,title="Main.js"]
----
export default function subtract(a, b) {
  return a - b;
}
----

In this case, the function is named (`subtract`), but it is exported as the default, so it can be imported with any name.
____
====

== Alias

https://stackoverflow.com/questions/39282253/how-can-i-alias-a-default-import-in-javascript[[source\]]

Non-default imports:

[,js]
----
import { foo as bar } from 'my-module';
----

Default import are already aliases:

[,js]
----
import alias from 'my-module';
// Or
import {default as alias} from 'my-module';
----