= Vite
:url-website: https://vite.dev/
:url-docs: https://vite.dev/guide/
:url-repo: https://github.com/vitejs/vite

{url-website}[[website\]]
{url-docs}[[docs\]]
{url-repo}[[repo\]]

https://github.com/vitejs/awesome-vite[[awesome-vite\]]

dev:: esbuild
prod:: Rollup

== Installation

[source,bash]
----
pnpm create vite@latest
----

// [source,bash]
// ----
// pnpm create vite-app PATH_TO_PRJ
// ----

[NOTE]
====
> "Vite projects using `Typescript` option use `Babel`, and using `Typescript + SWC` option use https://swc.rs/docs/getting-started[`SWC`]."
-- https://stackoverflow.com/questions/79111563/what-is-the-difference-of-typescript-vs-typescript-swc-when-creating-a-vite-pr
====

Create Vite + React:

[source,bash]
----
pnpm create vite --template react-ts
----

// [source,bash]
// ----
// # Create Vite + React app using npm
// npm create vite@latest vite-react-app -- --template react-ts
// 
// # Create Vite + React app using yarn
// yarn create vite --template react-ts
// ----

Run

[source,bash]
----
pnpm run dev
----

== Environment Variables

[quote,https://jasonwatmore.com/post/2022/05/28/vue-3-vite-access-environment-variables-from-dotenv-env]
____
Vite support `dotenv` environment variables out of the box, so all you need to do is add a `.env` file to the root folder of your [...] project.
____

[quote,https://jasonwatmore.com/post/2022/05/28/vue-3-vite-access-environment-variables-from-dotenv-env]
____
to access environment variables from the client app they must be prefixed with `VITE_`. 
Otherwise they will only be accessible on the server side.
____

.`.env`
----
VITE_MY_VAR='MY_VALUE'
----

[source,tsx]
----
const myVar = import.meta.env.VITE_MY_VAR;

export default function MyComponent() {

  return (
    <>
      {myVar}
    </>
  )
}
----

[source,vue]
----

<script setup>
const myVar = import.meta.env.VITE_MY_VAR;
</script>

<template>
    {{ myVar }}
</template>
----

== Filesystem

.Default (React)
....
./
├── public
│   └── ...
├── src
│   ├── assets
│   │   └── ...
│   ├── App.css
│   ├── App.tsx
│   ├── index.css
│   ├── main.tsx
│   └── vite-env.d.ts
├── README.md
├── eslint.config.js
├── index.html
├── package.json
├── tsconfig.app.json
├── tsconfig.json
├── tsconfig.node.json
└── vite.config.ts
....

== Minimal Project

=== React

....
react-project/
├── src/
│   ├── App.tsx
│   └── main.tsx
├── index.html
└── ...
....

[,javascript,title="App.tsx"]
----
function App() {
  return (
    <>
      {/* ... */}
    </>
  )
}

export default App
----

[,javascript,title="main.tsx"]
----
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
----

[,html,title="index.html"]
----
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <!-- <link rel="icon" type="image/x-icon" href="favicon.ico"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Minimal React Project</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
----
